


String = 'CTAAAGAGGACAGAATGGGCAGCGCTGCCGTGTTCTTAGGCGTATTGGGTCTTTCTCCCTGTTATAGCCCGCAGTGCTTTTTCGACATCACTCGTATGGAAAACAGCAAAGACGTGCGGCCGGGCATGTCATCCCATGTTGGGAAGCAGGATAGTCTCGTAGTCACAACGGAAAGTAAGTACTGCCATCTACCAGTTTTCCACATGCAGGCGCGACTTAAGCAAGATGCCTTAGGGTAATGCAACCATAGGGAGGTTCATCGGAATTTGTTTTAGTACGGCCAGCTTTTATTACCCTGGGCTCGGATAAGATCATACCCAACTTATAATGTTATAAGAATGCACTGAACCTAGGATCTTGGCATGTGACCTGCCAGGAGCCAATGCGTGGCAGAGTGTCATCGTGTAGTAACTAGGACCGCTGTCTCCACTCACCAACACGTATCAGCTCTTAGTCTCGATCTGCGTCACGGGTGCTATTCCTTGCCCTACCCAGGTCCCGAACCCATTAAAGTCCCTTCGATGATAAGTTGCCTATTTCCAGCGAATGCTCCCGACATCTCACATATAATATAACGATGTCAACGCTGGCCCGTTGGTGGTGTCAACAGTGTTTTACGCCTAGGCGCTTACTATTGCGAGTAGCAAAATTGATGTCACAGTTTCAAGGATGTGGCCCAAGAGAGATCTAAGAACTGCTATACACGATAGTATACTGAATGATCGCAAAGTCCTAAGCCCCGTTCAAATGTGGTACTAGTGCCTTGTGGGACTGCTACTAACTACGAGAGAAGGCGTGGCTCATTAAAATAAACAGCTGACTAAATCTACTGTGGTGTCAAAGGCATTGAGACCCCAAAAGCTTCCGCAAATCTAGGTCTAGTACTGCCTTGGCATGCTTGTCTGGTTTTCTTTAAAATGGTAACGGAGCTGTTAATAGTTCAGGGACGAACATCTGTTGAAGATA'
String2 = []

for x in String:
    if x == 'G':
        String2.append('T')
    if x == 'T':
        String2.append('G')
    if x == 'C':
        String2.append('A')
    if x == 'A':
        String2.append('C')
print ''.join(String2)